language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  fqdn: hexagonminecraft.com
  on:
    branch: master
